environment:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  TWILIO_ACCOUNT_PHONE_NUMBER: ${TWILIO_ACCOUNT_PHONE_NUMBER}
  DO_SPACES_KEY: ${DO_SPACES_KEY}
  DO_SPACES_SECRET: ${DO_SPACES_SECRET}
  STAGE: 'prod'

packages:
  - name: twilio
    functions:
      - name: twilio
        runtime: 'python:default'
        limits:
          memory: 384