environment:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  TWILIO_ACCOUNT_PHONE_NUMBER: ${TWILIO_ACCOUNT_PHONE_NUMBER}
  SENTRY_DSN: ${SENTRY_DSN}
  SENTRY_EVENT_LEVEL: ${SENTRY_EVENT_LEVEL}
  DO_SPACES_KEY: ${DO_SPACES_KEY}
  DO_SPACES_SECRET: ${DO_SPACES_SECRET}
  DO_BUCKET_NAME: ${DO_BUCKET_NAME}
  LOGGING_LEVEL: 'info'
  STAGE: 'prod'

packages:
  - name: edciowa
    functions:
      - name: texted
        runtime: 'python:3.11'
        limits:
          memory: 512